name: Bootstrap Infrastructure

on:
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TF_VAR_AWS_REGION }}

      - name: Initialize Backend
        run: ./init-backend.sh
